// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abdqbysxgrdkuzizweci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZHFieXN4Z3Jka3V6aXp3ZWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTUyMzUsImV4cCI6MjA2NDMzMTIzNX0.Og2h-dXz4pl1KjETTTCIaR-017Z6ZjKv62lowPF-ZCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);